# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: YandereDev.YandereSimulator.Launcher
PackageVersion: 2.12.0
PackageLocale: en-US
Publisher: YandereDev
PublisherUrl: https://yanderesimulator.com/
PublisherSupportUrl: https://yanderesimulator.com/contact/
PackageName: Yandere Simulator Launcher
PackageUrl: https://yanderesimulator.com/download/
License: Proprietary
Copyright: Â© 2014 - 2026 Yandere Simulator
ShortDescription: A launcher to Yandere Simulator game.
ReleaseNotesUrl: https://yanderesimulator.com/blog/
Documentations:
- DocumentLabel: FAQ
  DocumentUrl: https://yanderesimulator.com/about/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
