# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: SoftSea.UTMConverter
PackageVersion: "1.0"
PackageLocale: en-US
Publisher: SoftSea
PublisherUrl: https://www.softsea.com/
PublisherSupportUrl: https://www.softsea.com/contact.html
PrivacyUrl: https://www.softsea.com/privacy-policy.html
PackageName: UTM Converter
PackageUrl: https://www.softsea.com/software/UTM-Converter.html
License: Freeware
LicenseUrl: https://www.softsea.com/terms-of-use.html
Copyright: Copyright Â© 2006 - 2025 SoftSea.com. All rights reserved.
ShortDescription: A geographic coordinates converter
Description: UTM Converter is a geographic tool for converting UTM (Universal Transverse Mercator) coordinates to Lat/Long (Latitude/Longitude) coordinates, a free coordinates converter and calculator, can help you to quickly convert between Geographic and UTM Coordinates.
Moniker: utmconverter
Tags:
- softsea
- utm
- gps
- coordinates
- geographic
- convert
- converter
- utility
- tool
Documentations:
- DocumentLabel: Homepage
  DocumentUrl: https://www.utmconverter.com/
ManifestType: defaultLocale
ManifestVersion: 1.10.0
