# Created using wingetcreate 1.10.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: YandereDev.YandereSimulator
PackageVersion: 2026-01-01
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: YandereSimulator.exe
  PortableCommandAlias: YandereSimulator
Installers:
- Architecture: x64
  InstallerUrl: https://yanderesimulator.com/dl/latest.zip
  InstallerSha256: AC2B783115905B7F4FA7B5F6D63193F4776EF9725E273F5E3EA903956FB57510
ManifestType: installer
ManifestVersion: 1.10.0
ReleaseDate: 2026-01-01
